name: it-tools

services:
  tools:
    image: corentinth/it-tools:2024.10.22-7ca5933
    container_name: tools
    restart: unless-stopped
    networks:
      - traefik_internal
    labels:
      - "wud.autoupdate=true"
      - "wud.tag.include=^\\d{4}\\.\\d{2}\\.\\d{2}-[a-f0-9]{7}$$"
      - "traefik.enable=true"
      - "traefik.http.routers.tools-internal.entrypoints=websecure"
      - "traefik.http.routers.tools-internal.rule=Host(`tools.internal.pippinn.me`)"
      - "traefik.docker.network=traefik_internal"

networks:
  traefik_internal:
    external: true
