name: starr

services:
  radarr:
    image: ghcr.io/linuxserver/radarr:6.1.1.10360-ls299
    container_name: radarr
    restart: unless-stopped
    networks:
      - traefik_internal
    env_file:
      - ../../global.env
    volumes:
      - ./radarr-config:/config
      - /srv/dev-disk-by-uuid-f1209e02-5b26-491f-ac40-f951e9ddfbb0/movies:/movies
      - /srv/dev-disk-by-uuid-f1209e02-5b26-491f-ac40-f951e9ddfbb0/downloads-movies:/downloads/movies
      - /srv/dev-disk-by-uuid-0ddafbf7-f06d-424d-8e9c-95d97fbd4484/kids/movies:/kids/movies
      - /srv/dev-disk-by-uuid-f1209e02-5b26-491f-ac40-f951e9ddfbb0/downloads-kids-movies:/downloads/kids/movies
    labels:
      - "wud.autoupdate=true"
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.rule=Host(`radarr.internal.pippinn.me`)"
      - "traefik.docker.network=traefik_internal"
      - "wud.tag.include=^\\d+\\.\\d+\\.\\d+\\.\\d+-ls\\d+$$"
      - "wud.tag.transform=^(\\d+\\.\\d+\\.\\d+)\\.\\d+(-ls\\d+)$$ => $$1$$2"

  sonarr:
    image: ghcr.io/linuxserver/sonarr:4.0.17.2952-ls308
    container_name: sonarr
    restart: unless-stopped
    networks:
      - traefik_internal
    env_file:
      - ../../global.env
    volumes:
      - ./sonarr-config:/config
      - /srv/dev-disk-by-uuid-220b73c9-2682-4822-b871-cb499733b15b/tv:/tv
      - /srv/dev-disk-by-uuid-f1209e02-5b26-491f-ac40-f951e9ddfbb0/downloads-tv:/downloads/tv
    labels:
      - "wud.autoupdate=true"
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.internal.pippinn.me`)"
      - "traefik.docker.network=traefik_internal"
      - "wud.tag.include=^\\d+\\.\\d+\\.\\d+\\.\\d+-ls\\d+$$"
      - "wud.tag.transform=^(\\d+\\.\\d+\\.\\d+)\\.\\d+(-ls\\d+)$$ => $$1$$2"

  prowlarr:
    image: linuxserver/prowlarr:2.3.5.5327-ls142
    container_name: prowlarr
    restart: unless-stopped
    networks:
      - traefik_internal
    env_file:
      - ../../global.env
    volumes:
      - ./prowlarr-config:/config
    labels:
      - "wud.autoupdate=true"
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.internal.pippinn.me`)"
      - "traefik.docker.network=traefik_internal"
      - "wud.tag.include=^\\d+\\.\\d+\\.\\d+\\.\\d+-ls\\d+$$"
      - "wud.tag.transform=^(\\d+\\.\\d+\\.\\d+)\\.\\d+(-ls\\d+)$$ => $$1$$2"

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:5.1.4-r3-ls450
    container_name: qbittorrent
    restart: unless-stopped
    networks:
      - traefik_internal
    env_file:
      - ../../global.env
      - vars.env
    ports:
      - "32517:32517"
    volumes:
      - ./qbittorrent-config:/config
      - /srv/dev-disk-by-uuid-f1209e02-5b26-491f-ac40-f951e9ddfbb0/downloads-movies:/downloads/movies
      - /srv/dev-disk-by-uuid-f1209e02-5b26-491f-ac40-f951e9ddfbb0/downloads-tv:/downloads/tv
      - /srv/dev-disk-by-uuid-0ddafbf7-f06d-424d-8e9c-95d97fbd4484/kids:/downloads/kids
    labels:
      - "wud.autoupdate=true"
      - "traefik.enable=true"
      - "traefik.http.routers.torrent.entrypoints=websecure"
      - "traefik.http.routers.torrent.rule=Host(`torrent.internal.pippinn.me`)"
      - "traefik.http.services.torrent.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_internal"
      - "wud.tag.include=^\\d+\\.\\d+\\.\\d+-r\\d+-ls\\d+$$"

networks:
  traefik_internal:
    external: true
