name: plex

services:
  plex:
    image: ghcr.io/linuxserver/plex:1.43.4.10903-e5521bd8c-ls326
    container_name: plex
    restart: unless-stopped
    networks:
      - traefik_internal
    env_file:
      - ../../global.env
      - vars.env
    ports:
      - "32400:32400"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - ./config:/config
      - /mnt/storage/kids:/kids
      - /mnt/storage/movies:/movies
      - /mnt/storage/tv:/tv
    labels:
      - "wud.autoupdate=true"
      - "wud.tag.include=^\\d+\\.\\d+\\.\\d+\\.\\d+-[a-zA-Z0-9]+-ls\\d+$$"
      - "wud.tag.transform=^(\\d+\\.\\d+\\.\\d+)\\.\\d+-[a-zA-Z0-9]+(-ls\\d+)$$ => $$1$$2"
      - "traefik.enable=true"
      - "traefik.http.routers.plex-internal.entrypoints=websecure"
      - "traefik.http.routers.plex-internal.rule=Host(`plex.internal.pippinn.me`)"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.docker.network=traefik_internal"
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 512M

networks:
  traefik_internal:
    external: true
