- sensor:
  - name: "Word of the Day Part of Speech"
    unique_id: word_of_the_day_pos
    state: >
      {% set pos = state_attr('sensor.word_of_the_day', 'pos') %}
      {% if pos is not none %}
        {{ pos }}
      {% else %}
        None
      {% endif %}
- sensor:
  - name: "Word of the Day Gender"
    unique_id: word_of_the_day_gender
    state: >
      {% set gender = state_attr('sensor.word_of_the_day', 'gender') %}
      {% if gender is not none %}
        {{ gender }}
      {% else %}
        None
      {% endif %}
- sensor:
  - name: "Word of the Day Inflection"
    unique_id: word_of_the_day_stuttbeyg
    state: >
      {% set stuttbeyg = state_attr('sensor.word_of_the_day', 'stuttbeyg') %}
      {% if stuttbeyg is not none %}
        {{ stuttbeyg }}
      {% else %}
        None
      {% endif %}
- sensor:
  - name: "Word of the Day Translations"
    unique_id: word_of_the_day_translations
    state: >
      {% set translations = state_attr('sensor.word_of_the_day', 'translations') %}
      {% if translations %}
        {{ state_attr('sensor.word_of_the_day', 'translations') | join(', ') }}
      {% else %}
        None
      {% endif %}
- sensor:
  - name: "Word of the Day Example 1 IS"
    unique_id: word_of_the_day_example1_is
    state: >
      {% set ex = state_attr('sensor.word_of_the_day', 'examples') %}
      {% if ex and ex|length > 0 %}
        {{ ex[0]['is'] }}
      {% else %}
        None
      {% endif %}
- sensor:
  - name: "Word of the Day Example 1 SE"
    unique_id: word_of_the_day_example1_se
    state: >
      {% set ex = state_attr('sensor.word_of_the_day', 'examples') %}
      {% if ex and ex|length > 0 %}
        {{ ex[0]['se'] }}
      {% else %}
        None
      {% endif %}
- sensor:
  - name: "Word of the Day Example 2 IS"
    unique_id: word_of_the_day_example2_is
    state: >
      {% set ex = state_attr('sensor.word_of_the_day', 'examples') %}
      {% if ex and ex|length > 1 %}
        {{ ex[1]['is'] }}
      {% else %}
        None
      {% endif %}
- sensor:
  - name: "Word of the Day Example 2 SE"
    unique_id: word_of_the_day_example2_se
    state: >
      {% set ex = state_attr('sensor.word_of_the_day', 'examples') %}
      {% if ex and ex|length > 1 %}
        {{ ex[1]['se'] }}
      {% else %}
        None
      {% endif %}

