name: calibre-web

services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web:0.6.27-ls400
    container_name: calibre-web
    restart: unless-stopped
    networks:
      - traefik_internal
    env_file:
      - ../../global.env
      - vars.env
    volumes:
      - ./config:/config
      - /srv/dev-disk-by-uuid-f1209e02-5b26-491f-ac40-f951e9ddfbb0/books/ebooks:/ebooks:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
    labels:
      - "traefik.enable=false"
      - "wud.autoupdate=true"
      - "wud.tag.include=^\\d+\\.\\d+\\.\\d+-ls\\d+$$"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

networks:
  traefik_internal:
    external: true
