name: beszel

services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    environment:
      - APP_URL=https://monitoring.internal.pippinn.me
    ports:
      - "8090:8090"
    volumes:
      - ./data:/beszel_data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: 0.0.0.0:45876
      KEY: ${BESZEL_AGENT_KEY_PI}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
